[package]
authors = ["0shimax <shin.keeper@gmail.com>"]
name = "particle_filter"
version = "0.1.0"


[dependencies]
rand = "0.3.15"
rusty-machine = "0.5.3"
rayon = "0.6.0"

[features]
stats = ["rusty-machine/stats"]
